// <auto-generated />
using System;
using Hookpay.Modules.Notifications.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hookpay.Modules.Notifications.Core.Data.Migrations
{
    [DbContext(typeof(MessageDbContext))]
    [Migration("20250713133318_add_tbl_message_group")]
    partial class add_tbl_message_group
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hookpay.Modules.Notifications.Core.Models.InboxMessage", b =>
                {
                    b.Property<Guid>("correlationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("eventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("processed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("correlationId");

                    b.ToTable("inboxMessage");
                });

            modelBuilder.Entity("Hookpay.Modules.Notifications.Core.Models.Message", b =>
                {
                    b.Property<int>("mess_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("mess_id"));

                    b.Property<string>("mess_body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("mess_correlationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("mess_createdAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("mess_processed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("mess_title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("mess_userId")
                        .HasColumnType("int");

                    b.HasKey("mess_id");

                    b.HasIndex("mess_correlationId")
                        .IsUnique();

                    b.ToTable("message");
                });

            modelBuilder.Entity("Hookpay.Modules.Notifications.Core.Models.OutboxMessage", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<Guid>("correlationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("outboxMessage");
                });
#pragma warning restore 612, 618
        }
    }
}
