// <auto-generated />
using System;
using Hookpay.Modules.Topups.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hookpay.Modules.Topups.Core.Data.Migrations
{
    [DbContext(typeof(TopupDbContext))]
    partial class TopupDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hookpay.Modules.Topups.Core.Topups.Models.Topup", b =>
                {
                    b.Property<int>("topup_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("topup_id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("topup_creator")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("topup_source")
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("topup_tranfer_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("topup_trans_id")
                        .HasColumnType("int");

                    b.HasKey("topup_id");

                    b.HasIndex("topup_trans_id")
                        .IsUnique();

                    b.ToTable("Topup", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
